config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => {registrations: 'registrations'}
resources :users, :only => [:show]

get "tags/:tag", to: "stories#index", as: :tag
get "users/:id", to: "registrations#show" 

resources :stories do
	member do
		get 'like', to: 'stories#upvote'
		get 'dislike', to: 'stories#downvote'
	end
	resources :comments
end

authenticated :user do
	root 'stories#index', as: "authenticated_root"
end

root 'front_pages#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story
end

app/models/story.rb
class Story < ActiveRecord::Base

	belongs_to :user
	has_many :comments, :dependent => :delete_all
	acts_as_taggable
	acts_as_votable
	validates :title, presence: true
	validates :content, presence: true
	validates :tag_list, presence: true

end

app/models/user.rb
  class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stories

  has_attached_file :avatar,
  				          :styles => { :medium => "300x300#", 
  				    			             :thumb => "100x100#" },
                    :storage => :s3,
                    :s3_permissions => :private,
                    :s3_protocol => 'https',
                    :s3_host_name => ENV['AWS_HOST_NAME']

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@story = Story.find(params[:story_id])
		@comments = @story.comments.create(params[:comment].permit(:name, :body))

		redirect_to story_path(@story) 
	end
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController

	def index		
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:first_name, :last_name, :username, :email, :biography, :password, :password_confirmation, :avatar)
	end

	def account_update_params
		params.require(:user).permit(:first_name, :last_name, :username, :email, :biography, :password, :password_confirmation, :current_password, :avatar)
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	layout 'application'

	before_action :find_story, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!


	def index
		if params[:tag]
			@stories = Story.all.order("created_at DESC").tagged_with(params[:tag])
		else
			@stories = Story.all.order("created_at DESC")
		end

	end

	def show
		
	end

	def new
		@story = current_user.stories.build
	end

	def create
		@story = current_user.stories.build(story_params)
		if @story.save
			redirect_to @story
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @story.update(story_params)
			redirect_to @story
		else
			render 'edit'
		end
	end

	def destroy
		@story.destroy
		redirect_to stories_path
	end

	def upvote
		@story.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@story.downvote_by current_user
		redirect_to :back
	end


private
	
	def find_story
		@story = Story.find(params[:id])
	end

	def story_params
		params.require(:story).permit(:title, :tag_list, :content, :user_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def devise_flash
  		if controller.devise_controller? && resource.errors.any?
    		flash.now[:error] = flash[:error].to_a.concat resource.errors.full_messages
    		flash.now[:error].uniq!
  		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
  end
end

app/helpers/front_pages_helper.rb
module FrontPagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_comment.html.haml
.container
	.row
		.col-md-6.offset-md-6
			%h5= "Commented by: #{comment.name}"
			%p= comment.body
			%br/
			%p= "#{time_ago_in_words(comment.created_at)} ago"

app/views/comments/_form.html.haml
= simple_form_for [@story, @story.comments.build] do |f|
	
	=f.input :name, label: "Your name:"
	=f.input :body, label: "Your comment"
	=f.button :submit

app/views/front_pages/index.html.haml
.my-background
	.container
		%h1.heading Every story needs
		%h2.sub-heading to be told
		%br/
		.btn.btn-lg.my-button
			= link_to "Tell us one story", stories_path, class: "my-button"

app/views/layouts/_messages.html.erb
<% devise_flash %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= value %>
  </div>
<% end %>

app/views/layouts/application.html.haml
!!!5
%html
	%head
		%title Tellme
	= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Montserrat'
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
	%body
		%nav.navbar-inverse.navbar-fixed-top
			
			.navbar-brand.my-brand= link_to "TELL.ME", stories_path
			%ul.nav.navbar-nav.navbar-right.my-links

				- if user_signed_in?
					%li= link_to "My Profile", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
					%li.round-image-50= image_tag(current_user.avatar.url(:thumb, timestamp: false))
				- else
					%li= link_to "Sign In", new_user_session_path
					%li= link_to "Sign Up", new_user_registration_path
						

		.container
			= render 'layouts/messages'

		= yield


		.my-footer
			.nav.navbar-inverse.navbar-fixed-bottom
				%p Developed by: Eduardo Martins

app/views/stories/_form.html.haml
= simple_form_for @story do |f|
	=f.input :title
	=f.input :tag_list, label: "Tags: (separated by commas)" 
	=f.input :content, input_html: {:rows => 15}

	
	=f.button :submit, class: "btn btn-success"

app/views/stories/edit.html.haml
.container
	.row.marging-bottom
		%h1 Edit your story:

		= render 'form'

app/views/stories/index.html.haml
.container
	%h1 The Stories Room
	= link_to "Tell a new Story", new_story_path, class: "btn btn-lg my-button"
	%hr/
	.row.marging-bottom
		.col-md-4
			%h2 About TellMe
			%p This app is about writing and reading. I believe that every story needs to be told. Founded in this kind of think i decide create this app.
			Anyone can write, anyone can read!
			All of you are welcome! Fells like in my room, in my house, and just tell me about anything that you want. About yourself, about happynes, about sadnes, love, to make us laugh or cry.
			one more time, you are welcome!
			%br/
			%br/
			Eduardo Martins.
		.col-md-6.stories
			- @stories.each do |story|	
				.center-text
					%h1.my-title= link_to story.title, story_path(story), class: "story-title"
					%br/
					%p.left-text 
						Tags:
						= raw story.tag_list.map{ |t| link_to t, tag_path(t)}.join(', ')
					%p.left-text
						= pluralize(story.get_likes.size,'Like')
				%hr/
				
		.col-md-2
			%h3 Tag Cloud:
			#tag_cloud
				- tag_cloud(Story.tag_counts, %w(css1, css2, css3, css4)) do |tag, css_class|
					= link_to tag.name, tag_path(tag.name), :class => css_class
				%br/
				%br/
				= link_to "All Stories", stories_path

	
	

app/views/stories/new.html.haml
.container
	.row.marging-bottom
		%h1 Tell your story:

		= render 'form'
		%br/
		=link_to "Back to Stories", stories_path, class: "btn btn-primary"

app/views/stories/show.html.haml
.container
	.row.marging-bottom
		%h1= @story.title
		%h4= link_to "by #{@story.user.first_name} #{@story.user.last_name}", :controller => 'users', :action => 'show', :id => @story.user.id

		%p= simple_format @story.content

		%p
			= pluralize(@story.get_upvotes.size, 'Like')
		%p
			= pluralize(@story.get_downvotes.size, 'Dislike')

		%button.btn.btn-default
			%span.glyphicon.glyphicon-heart= link_to "  Like", like_story_path(@story), method: :get
		%button.btn.btn-default
			%span.glyphicon.glyphicon-heart-empty= link_to "  Dislike", dislike_story_path(@story), method: :get

		%br/
		%h3 Comments
		%p= "#{@story.comments.count} comments."
		= render @story.comments
		
		- if user_signed_in?
			%hr/
			%h2 Leave a comment
			= render 'comments/form'
		- else
			%h2 Log in to leave a comment




		%br/
		%br/

		- if (current_user.id == @story.user.id)
			= link_to 'Edit', edit_story_path(@story), class: "btn btn-primary"
			= link_to 'Delete', story_path(@story), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"

		%br/
		%br/

		= link_to "Back to Stories", stories_path, class: "btn btn-primary"

app/views/users/show.html.haml
.container.container-color
	.row
		.col-md-4.col-md-offset-2
			= image_tag(@user.avatar.url(:medium), class: "profile-picture")

		.col-md-4
			%h1.color-name My stories:
			- @user.stories.each do |story|
				%p= link_to story.title, :controller => 'stories', :action => 'show', :id => story.id

			%br/
			%br/
			= link_to "Back to Stories", stories_path, class: "btn btn-primary"

	.row
		.col-md-4.col-md-offset-2
			%br/
			%hr/
			%hr/
			%h4.color-name Name: 
			= "#{@user.first_name} #{@user.last_name}" 
			%br/
			%h4.color-name About me:
			%p= @user.biography

	.row
		.col-md-4.col-md-offset-2
			%br/
			